### ISSUE TITLE
Does not build on SBCL - defconstant issue

### ISSUE THREAD

**Issue by quicklisp** [nakrakiiya/cl-prime-maker#1]
http://report.quicklisp.org/2015-02-12/failure-report/cl-prime-maker.html#cl-prime-maker has a log of the build failure - basically, SBCL does not accept multiple defconstant forms (in this case at compile time and load time) unless the data is EQL.

http://www.sbcl.org/manual/#Defining-Constants has some information about the issue

**Comment by lispfaq** [comment]
FIXED in truck. Now it could be compiled and be loaded.
Tested with SBCL 1.2.7, CCL 1.10, ABCL 1.3.1.

**Comment by nakrakiiya** [comment]
FIXED in truck. Now it could be compiled and be loaded.
Tested with SBCL 1.2.7, CCL 1.10, ABCL 1.3.1.
